name: 合并与部署网站

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 内容源码SHA
        required: false
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    env:
      HUGO_CACHEDIR: /tmp/hugo_cache
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: 显示信息
        run: |
          echo "内容源码SHA: ${{ github.event.inputs.sha }}"

      - name: 提取
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 提取内容源码
        uses: actions/checkout@v5
        with:
          repository: xfqwdsj/LearningNotes
          token: ${{ secrets.SOURCE_PAT }}
          ref: ${{ github.event.inputs.sha }}
          path: content

      - name: 强制推送到本仓库merged分支
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan merged
          rm -rf .github
          rm -rf content/.git
          rm -rf content/.github
          git add .
          git commit -m "Merge content from xfqwdsj/LearningNotes at ${{ github.event.inputs.sha }} [skip ci]"
          git push -f origin merged

      - name: 设置Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: 设置Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: 设置缓存
        uses: actions/cache@v4
        with:
          path: ${{ env.HUGO_CACHEDIR }}
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: 构建网站
        run: hugo --minify

      - name: 上传产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
