name: 合并网站

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 内容源码SHA
        required: true

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: 显示信息
        run: |
          echo "内容源码SHA: ${{ github.event.inputs.sha }}"
      
      - name: 提取
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 提取内容源码
        uses: actions/checkout@v4
        with:
          repository: xfqwdsj/LearningNotes
          token: ${{ secrets.SOURCE_PAT }}
          ref: ${{ github.event.inputs.sha }}
          path: content

      - name: 强制推送到本仓库merged分支
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan merged
          rm -rf .github
          rm -rf content/.git
          git add .
          git commit -m "Merge content from xfqwdsj/LearningNotes at ${{ github.event.inputs.sha }} [skip ci]"
          git push -f origin merged

      - name: 设置Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: 编译Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true
          source-dir: ./
          destination-dir: ./public
          args: --minify

      - name: 上传产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
